// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using budgetmanagementAngular.data;

namespace budgetmanagementAngular.Migrations
{
    [DbContext(typeof(budgetContext))]
    [Migration("20180422195406_deleteUsers")]
    partial class deleteUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("budgetmanagementAngular.data.budget", b =>
                {
                    b.Property<int>("budgetID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("creationDate");

                    b.Property<int>("month");

                    b.Property<decimal>("totalIncome")
                        .HasColumnType("money");

                    b.Property<string>("userID");

                    b.Property<int>("year");

                    b.HasKey("budgetID");

                    b.ToTable("budgets");
                });

            modelBuilder.Entity("budgetmanagementAngular.data.budgetCategory", b =>
                {
                    b.Property<int>("budgetCategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("amount")
                        .HasColumnType("money");

                    b.Property<int>("budgetID");

                    b.Property<bool>("isRecurring");

                    b.Property<string>("name");

                    b.HasKey("budgetCategoryID");

                    b.HasIndex("budgetID");

                    b.ToTable("budgetCategories");
                });

            modelBuilder.Entity("budgetmanagementAngular.data.budgetCategory", b =>
                {
                    b.HasOne("budgetmanagementAngular.data.budget", "budget")
                        .WithMany("categories")
                        .HasForeignKey("budgetID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
